# Generated by Django 5.2.4 on 2025-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
