# Generated by Django 5.2.4 on 2025-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_testimonials_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('link', models.URLField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
